[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.7", features = [ "runtime-tokio", "sqlite", "migrate", "uuid", "chrono" ] }
tokio = { version = "1", features = ["full"] }
serde = "1.0.197"
serde_json = "1.0.114"
sha2 = "0.10.8"
hex = "0.4.3"